onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/data}
add wave -noupdate -divider =======================HIDDEN_LAYER_NEURONS=======================
add wave -noupdate -divider Neuron0
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/weight_from_rom}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/selected_weights}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/result}
add wave -noupdate -divider debug
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/clk}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/reset}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/data}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_0}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_1}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_2}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_3}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_4}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_5}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_6}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_7}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_8}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_9}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_10}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_11}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_12}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_13}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_14}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_15}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_16}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_17}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_18}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_19}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_20}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_21}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_22}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_23}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_24}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_25}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_26}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_27}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_28}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_29}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_30}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_31}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_32}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_33}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_34}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_35}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_36}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_37}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_38}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_39}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_40}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_41}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_42}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_43}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_44}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_45}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_46}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_47}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_48}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_49}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_50}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_51}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_52}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_53}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_54}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_55}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_56}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_57}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_58}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_59}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_60}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_61}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_62}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_weight_from_rom_63}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/result}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/weight_from_rom}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/rom_data}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/selected_weights}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_partial_sum_stage1}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_partial_sum_stage2}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_partial_sum_stage3}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_partial_sum_stage4}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_partial_sum_stage5}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[0]/hidden_layer_neuron/wire_result}
add wave -noupdate -divider Neuron1
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[1]/hidden_layer_neuron/weight_from_rom}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[1]/hidden_layer_neuron/selected_weights}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[1]/hidden_layer_neuron/result}
add wave -noupdate -divider Neuron2
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[2]/hidden_layer_neuron/weight_from_rom}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[2]/hidden_layer_neuron/selected_weights}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[2]/hidden_layer_neuron/result}
add wave -noupdate -divider Neuron3
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[3]/hidden_layer_neuron/weight_from_rom}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[3]/hidden_layer_neuron/selected_weights}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[3]/hidden_layer_neuron/result}
add wave -noupdate -divider Neuron4
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[4]/hidden_layer_neuron/weight_from_rom}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[4]/hidden_layer_neuron/selected_weights}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[4]/hidden_layer_neuron/result}
add wave -noupdate -divider Neuron5
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[5]/hidden_layer_neuron/weight_from_rom}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[5]/hidden_layer_neuron/selected_weights}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[5]/hidden_layer_neuron/result}
add wave -noupdate -divider Neuron6
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[6]/hidden_layer_neuron/weight_from_rom}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[6]/hidden_layer_neuron/selected_weights}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[6]/hidden_layer_neuron/result}
add wave -noupdate -divider Neuron7
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[7]/hidden_layer_neuron/weight_from_rom}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[7]/hidden_layer_neuron/selected_weights}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[7]/hidden_layer_neuron/result}
add wave -noupdate -divider Neuron8
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[8]/hidden_layer_neuron/weight_from_rom}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[8]/hidden_layer_neuron/selected_weights}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[8]/hidden_layer_neuron/result}
add wave -noupdate -divider Neuron9
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[9]/hidden_layer_neuron/weight_from_rom}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[9]/hidden_layer_neuron/selected_weights}
add wave -noupdate {/tb_NPU_top/uut/gen_hidden_layer[9]/hidden_layer_neuron/result}
add wave -noupdate -divider =======================RELUS=======================
add wave -noupdate -divider ReLu0
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[0]/ReLu/data_in}
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[0]/ReLu/result}
add wave -noupdate -divider ReLu1
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[1]/ReLu/data_in}
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[1]/ReLu/result}
add wave -noupdate -divider ReLu2
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[2]/ReLu/data_in}
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[2]/ReLu/result}
add wave -noupdate -divider ReLu3
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[3]/ReLu/data_in}
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[3]/ReLu/result}
add wave -noupdate -divider ReLu4
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[4]/ReLu/data_in}
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[4]/ReLu/result}
add wave -noupdate -divider ReLu5
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[5]/ReLu/data_in}
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[5]/ReLu/result}
add wave -noupdate -divider ReLu6
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[6]/ReLu/data_in}
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[6]/ReLu/result}
add wave -noupdate -divider ReLu7
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[7]/ReLu/data_in}
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[7]/ReLu/result}
add wave -noupdate -divider ReLu8
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[8]/ReLu/data_in}
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[8]/ReLu/result}
add wave -noupdate -divider ReLu9
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[9]/ReLu/data_in}
add wave -noupdate {/tb_NPU_top/uut/gen_ReLu[9]/ReLu/result}
add wave -noupdate -divider =======================OUTPUT_LAYER=======================
add wave -noupdate -divider OutputNeuron0
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[0]/Output_Layer_Neuron/result}
add wave -noupdate -divider OutputNeuron1
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[1]/Output_Layer_Neuron/result}
add wave -noupdate -divider OutputNeuron2
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[2]/Output_Layer_Neuron/result}
add wave -noupdate -divider OutputNeuron3
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[3]/Output_Layer_Neuron/result}
add wave -noupdate -divider OutputNeuron4
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[4]/Output_Layer_Neuron/result}
add wave -noupdate -divider OutputNeuron5
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[5]/Output_Layer_Neuron/result}
add wave -noupdate -divider OutputNeuron6
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[6]/Output_Layer_Neuron/result}
add wave -noupdate -divider OutputNeuron7
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/result}
add wave -noupdate -divider debug
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/result}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/wire_product}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/wire_stage1_sum}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/wire_stage2_sum}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/wire_stage3_sum}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/wire_stage4_sum}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/stage3_sum}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[7]/Output_Layer_Neuron/stage4_sum}
add wave -noupdate -divider OutputNeruon8
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[8]/Output_Layer_Neuron/result}
add wave -noupdate -divider OutputNeuron9
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_top/uut/output_neuron[9]/Output_Layer_Neuron/result}
add wave -noupdate -divider {Final Inference}
add wave -noupdate /tb_NPU_top/uut/Final_Inference/prediction
add wave -noupdate /tb_NPU_top/uut/Final_Inference/final_computation
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {570 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 449
configure wave -valuecolwidth 292
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1428 ns}
