
`define MEMORY_SIZE 4096
`define ADDR_WIDTH $clog2(`MEMORY_SIZE)
`define DATA_WIDTH 64
`define OFFSET 8

`define CPCI_NF2_DATA_WIDTH 32
`define UDP_REG_ADDR_WIDTH 32
`define ILA_TOP_REG_ADDR_WIDTH 32
`define ILA_TOP_BLOCK_ADDR 18'h00006

`define COUNTER_DISABLE_TEST 0
