onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider HLN3
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/clk}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/reset}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/data}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_10}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_11}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_12}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_13}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_14}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_15}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_16}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_17}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_18}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_19}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_20}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_21}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_22}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_23}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_24}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_25}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_26}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_27}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_28}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_29}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_30}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_31}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_32}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_33}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_34}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_35}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_36}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_37}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_38}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_39}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_40}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_41}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_42}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_43}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_44}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_45}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_46}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_47}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_48}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_49}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_50}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_51}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_52}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_53}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_54}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_55}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_56}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_57}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_58}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_59}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_60}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_61}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_62}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_weight_from_rom_63}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/result}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/weight_from_rom}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/bfloat16_sum}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/wire_mux_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/acc}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/state}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/index}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/reg_data}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/mux_select}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/mux_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/reg_mux_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/b}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/a}
add wave -noupdate -divider {HLN3 ADDER}
add wave -noupdate -radix hexadecimal {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/a}
add wave -noupdate -radix hexadecimal {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/b}
add wave -noupdate -radix hexadecimal {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/result}
add wave -noupdate -radix binary {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/sign_a}
add wave -noupdate -radix binary {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/sign_b}
add wave -noupdate -radix binary {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/mant_a}
add wave -noupdate -radix binary {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/mant_b}
add wave -noupdate -radix binary {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/exp_a}
add wave -noupdate -radix binary {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/exp_b}
add wave -noupdate -radix binary {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/hiddenbit_mant_a}
add wave -noupdate -radix binary {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/hiddenbit_mant_b}
add wave -noupdate -radix binary {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/inter_mant_a}
add wave -noupdate -radix binary {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/inter_mant_b}
add wave -noupdate -radix binary {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/mant_shift_amt}
add wave -noupdate -radix binary {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/normalization_shift}
add wave -noupdate -radix binary {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/sum_mant}
add wave -noupdate -radix binary {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/final_exp}
add wave -noupdate -radix binary {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/final_mant}
add wave -noupdate -radix binary {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/final_sign}
add wave -noupdate -radix binary {/tb_NPU_pipeline_top/uut/NPU_top/gen_hidden_layer[3]/hidden_layer_neuron/adder_inst/i}
add wave -noupdate -divider OLN0
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/result}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/wire_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/wire_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/bfloat8_sum}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/wire_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/acc}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/reg_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/select_reg_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/reg_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/state}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/index}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/b}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[0]/Output_Layer_Neuron/a}
add wave -noupdate -divider OLN1
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/result}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/wire_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/wire_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/bfloat8_sum}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/wire_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/acc}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/reg_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/select_reg_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/reg_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/state}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/index}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/b}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[1]/Output_Layer_Neuron/a}
add wave -noupdate -divider OLN2
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/result}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/wire_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/wire_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/bfloat8_sum}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/wire_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/acc}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/reg_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/select_reg_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/reg_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/state}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/index}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/b}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[2]/Output_Layer_Neuron/a}
add wave -noupdate -divider OLN3
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/result}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/wire_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/wire_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/bfloat8_sum}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/wire_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/acc}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/reg_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/select_reg_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/reg_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/state}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/index}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/b}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[3]/Output_Layer_Neuron/a}
add wave -noupdate -divider OLN4
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/result}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/wire_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/wire_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/bfloat8_sum}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/wire_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/acc}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/reg_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/select_reg_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/reg_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/state}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/index}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/b}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[4]/Output_Layer_Neuron/a}
add wave -noupdate -divider OLN5
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/result}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/wire_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/wire_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/bfloat8_sum}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/wire_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/acc}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/reg_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/select_reg_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/reg_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/state}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/index}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/b}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[5]/Output_Layer_Neuron/a}
add wave -noupdate -divider OLN6
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/result}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/wire_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/wire_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/bfloat8_sum}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/wire_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/acc}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/reg_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/select_reg_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/reg_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/state}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/index}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/b}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[6]/Output_Layer_Neuron/a}
add wave -noupdate -divider OLN7
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/result}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/wire_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/wire_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/bfloat8_sum}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/wire_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/acc}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/reg_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/select_reg_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/reg_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/state}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/index}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/b}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[7]/Output_Layer_Neuron/a}
add wave -noupdate -divider OLN8
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/result}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/wire_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/wire_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/bfloat8_sum}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/wire_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/acc}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/reg_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/select_reg_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/reg_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/state}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/index}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/b}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[8]/Output_Layer_Neuron/a}
add wave -noupdate -divider OLN9
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/clk}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/reset}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/ReLu0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/ReLu1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/ReLu2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/ReLu3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/ReLu4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/ReLu5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/ReLu6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/ReLu7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/ReLu8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/ReLu9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/Weight0}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/Weight1}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/Weight2}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/Weight3}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/Weight4}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/Weight5}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/Weight6}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/Weight7}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/Weight8}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/Weight9}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/result}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/wire_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/wire_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/bfloat8_sum}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/wire_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/acc}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/reg_product}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/select_reg_relu}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/reg_weight}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/state}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/index}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/b}
add wave -noupdate {/tb_NPU_pipeline_top/uut/NPU_top/output_neuron[9]/Output_Layer_Neuron/a}
add wave -noupdate -divider {FINAL INFERENCE}
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/clk
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/reset
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/input_0
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/input_1
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/input_2
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/input_3
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/input_4
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/input_5
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/input_6
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/input_7
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/input_8
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/input_9
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/prediction
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/final_computation
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/max_0_1
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/max_2_3
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/max_4_5
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/max_6_7
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/max_8_9
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/max_0_3
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/max_4_7
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/max_0_7
add wave -noupdate /tb_NPU_pipeline_top/uut/NPU_top/Final_Inference/max_0_9
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {6996 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 449
configure wave -valuecolwidth 292
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {6946 ns} {7224 ns}
